// <auto-generated />
using System;
using DebateAnalyzer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DebateAnalyzer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DebateAnalyzerDbContext))]
    [Migration("20260802153603_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioBlobUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryText")
                        .HasColumnType("text");

                    b.Property<int?>("TranscriptionProgressSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("Claim");
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.Fallacy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("Fallacy");
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.KeyMoment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("KeyMoment");
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.Speaker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("Speaker");
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.TranscriptSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("TranscriptSegment");
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.Analysis", b =>
                {
                    b.OwnsOne("DebateAnalyzer.Domain.ValueObjects.VideoMetadata", "Video", b1 =>
                        {
                            b1.Property<Guid>("AnalysisId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("DurationSeconds")
                                .HasColumnType("integer");

                            b1.Property<string>("SourceName")
                                .HasColumnType("text");

                            b1.Property<string>("ThumbnailUrl")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.Property<string>("YouTubeUrl")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("YouTubeVideoId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AnalysisId");

                            b1.ToTable("Analyses");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisId");
                        });

                    b.Navigation("Video")
                        .IsRequired();
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.Claim", b =>
                {
                    b.HasOne("DebateAnalyzer.Domain.Entities.Analysis", null)
                        .WithMany("Claims")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.Fallacy", b =>
                {
                    b.HasOne("DebateAnalyzer.Domain.Entities.Analysis", null)
                        .WithMany("Fallacies")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.KeyMoment", b =>
                {
                    b.HasOne("DebateAnalyzer.Domain.Entities.Analysis", null)
                        .WithMany("KeyMoments")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.Speaker", b =>
                {
                    b.HasOne("DebateAnalyzer.Domain.Entities.Analysis", null)
                        .WithMany("Speakers")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.TranscriptSegment", b =>
                {
                    b.HasOne("DebateAnalyzer.Domain.Entities.Analysis", null)
                        .WithMany("TranscriptSegments")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DebateAnalyzer.Domain.Entities.Analysis", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Fallacies");

                    b.Navigation("KeyMoments");

                    b.Navigation("Speakers");

                    b.Navigation("TranscriptSegments");
                });
#pragma warning restore 612, 618
        }
    }
}
