<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Asp.Versioning.Http" Version="10.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\App.ServiceDefaults\App.ServiceDefaults.csproj" />
    <ProjectReference Include="..\DebateAnalyzer.Application\DebateAnalyzer.Application.csproj" />
    <ProjectReference Include="..\DebateAnalyzer.Infrastructure\DebateAnalyzer.Infrastructure.csproj" />
  </ItemGroup>

</Project>
